# Generated by Django 3.2 on 2022-12-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
