# Generated by Django 3.2 on 2022-12-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='views',
            new_name='views_total',
        ),
        migrations.AddField(
            model_name='noticia',
            name='views_week',
            field=models.IntegerField(default=0),
        ),
    ]
