# Generated by Django 3.2 on 2022-12-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20221219_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
    ]
